# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pivotal-to-trello 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "pivotal-to-trello"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dave Perrett"]
  s.date = "2014-01-13"
  s.description = "Pulls pivotal tracker stories and imports them into Trello"
  s.email = "hello@daveperrett.com"
  s.executables = ["pivotal-to-trello"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/pivotal-to-trello",
    "lib/pivotal-to-trello.rb",
    "lib/pivotal_to_trello/core.rb",
    "lib/pivotal_to_trello/runner.rb",
    "pivotal-to-trello.gemspec",
    "spec/pivotal-to-trello_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/recurser/pivotal-to-trello"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "Pivotal Tracker to Trello exporter"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-trello>, [">= 0"])
      s.add_runtime_dependency(%q<pivotal-tracker>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<ruby-trello>, [">= 0"])
      s.add_dependency(%q<pivotal-tracker>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-trello>, [">= 0"])
    s.add_dependency(%q<pivotal-tracker>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

